### ISSUE TITLE
Add TokenStore

### ISSUE THREAD

**Issue by snakedye** [Byzantium-ETS/amper#5]
This will replace or rather will take some responsibility off the `SecretStore` interface.

## Tasks

* [ ] Create the interface.
* [ ] A `TokenStore` implementation.
* [ ] Write a mock `TokenStore`
* [ ] Make tests for the proper `TokenStore` implementation

## Requirements

* Store the tokens on the disk (local)
* One file per token
* The filename should be identifiable
* Only valid tokens should be **stored** (they can become invalidated later on)
